// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 8/5/2025, 9:55:35 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/acl/Development/consultoria/inaplast/liberador_inaplast_nuxt/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/acl/Development/consultoria/inaplast/liberador_inaplast_nuxt/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/acl/Development/consultoria/inaplast/liberador_inaplast_nuxt/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/acl/Development/consultoria/inaplast/liberador_inaplast_nuxt/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/acl/Development/consultoria/inaplast/liberador_inaplast_nuxt/app/plugins/**/*.{js,ts,mjs}","/Users/acl/Development/consultoria/inaplast/liberador_inaplast_nuxt/app/composables/**/*.{js,ts,mjs}","/Users/acl/Development/consultoria/inaplast/liberador_inaplast_nuxt/app/utils/**/*.{js,ts,mjs}","/Users/acl/Development/consultoria/inaplast/liberador_inaplast_nuxt/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/acl/Development/consultoria/inaplast/liberador_inaplast_nuxt/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/acl/Development/consultoria/inaplast/liberador_inaplast_nuxt/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/acl/Development/consultoria/inaplast/liberador_inaplast_nuxt/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;